language: python
python:
- '3.7'
script: true
before_deploy:
- cd rdfizer/
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  user: __token__
  password: 
    secure: "PNhrET9BYdNA/TNlnVCzFSe6IO37nm4fFStyZKaBpXtji22jFqmz+Mi6/Li6Q7Jvansh4KOqnTW3p6MskxDN9Dgt3KMedCX/F9b8hzl3C4rnoQi8oYITy1rpZ282md/rjcMHQoa9hYH1ztz+b1yHENOkKh21+hT0QuLhGneGKd8iigD+MzvcMoS5yTgGvhuhrPJfRWTyasumAUDqGgRKVDyw1Z6+oYE7vH0lukGMhIF+Krald3neTk+tODe6fDoJfa1eahwRpJbAs/x5hxUSjE032GV5AfohlTtb81rIDQZrz4R84b/h8k+f3CIz5d5brcbWud7nmsTXblqYfefVTrR5nu6VDDLH/HKbEtn26ydRZoDorlSc6yyKHDPwzS/PIQoZTEoCUXU08zMQOs2g+JYbTJrLUU5It8ine3u7EMWdNAPDtC2+BQthYuGpfLntfnpgzD2A2ujSqRTKfHboPakfLngWTALlN4dgsqzTMGBGeXXbKx3Q6+SLngjHNNzWrWcgUuTRJbr+WyS3uQIcEZ4vBaGLOBlIxsm/RTxa9sS6xLVOtTZ6JDR2vvUS+PnNY6wTKjkFiM4bjvkUU5Tw8W8B37nT/gjKz3dbfyqyuQLu2CyuIbZJm761J6KrpJuiLNp7xmwLnSMRXo2Y3YoBsAFKC/JQ83ZHyfsWmRjR7nk="
